"""
Predefined response database for the rule-based chatbot.
Portfolio-themed intents for Carson's personal portfolio assistant.
"""

INTENT_KEYWORDS = {
    "greeting": {
        "message": [
            "hello",
            "hi",
            "hey",
            "greetings",
            "howdy",
            "sup",
            "yo",
        ],
    },
    "about": {
        "info": [
            "who",
            "about",
            "yourself",
            "background",
            "introduction",
            "introduce",
            "biography",
            "bio",
            "person",
            "carson",
            "lok",
        ],
    },
    "skills": {
        "technical": [
            "skill",
            "skills",
            "tech",
            "technology",
            "language",
            "languages",
            "framework",
            "frameworks",
            "tools",
            "stack",
            "proficient",
            "know",
            "coding",
            "programming",
            "python",
            "javascript",
            "react",
            "mysql",
            "c++",
        ],
    },
    "projects": {
        "work": [
            "project",
            "projects",
            "built",
            "made",
            "created",
            "portfolio",
            "app",
            "application",
            "developed",
            "build",
            "work",
            "showcase",
        ],
    },
    "experience": {
        "job": [
            "experience",
            "job",
            "internship",
            "intern",
            "position",
            "role",
            "company",
            "career",
            "worked",
            "employment",
            "professional",
        ],
    },
    "education": {
        "school": [
            "education",
            "school",
            "university",
            "college",
            "degree",
            "study",
            "studied",
            "major",
            "course",
            "ontario",
            "student",
            "graduate",
        ],
    },
    "contact": {
        "reach": [
            "contact",
            "reach",
            "email",
            "linkedin",
            "github",
            "instagram",
            "social",
            "connect",
            "message",
            "touch",
            "find",
            "link",
        ],
    },
    "resume": {
        "cv": [
            "resume",
            "cv",
            "download",
            "pdf",
            "hire",
            "hiring",
            "curriculum",
        ],
    },
}

STOP_WORDS = [
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "but",
    "by",
    "can",
    "could",
    "do",
    "for",
    "from",
    "get",
    "give",
    "has",
    "have",
    "help",
    "how",
    "i",
    "in",
    "is",
    "it",
    "like",
    "me",
    "my",
    "of",
    "on",
    "or",
    "our",
    "please",
    "tell",
    "than",
    "that",
    "the",
    "their",
    "there",
    "this",
    "to",
    "us",
    "want",
    "was",
    "we",
    "what",
    "when",
    "where",
    "which",
    "with",
    "would",
    "you",
    "your",
]

PORTFOLIO_INFO = {
    "greeting": {
        "responses": [
            "Hi! I'm Carson's assistant. Ask me about his skills, projects, resume, or how to get in touch.",
            "Hey there! I can tell you about Carson's background, skills, projects, or experience.",
            "Hello! What would you like to know about Carson?",
        ],
    },
    "about": {
        "response": "Carson (Lok Yung Chan) is a 3rd year Software Engineering student at Ontario Tech University. He's passionate about full-stack development, agile practices, and CI/CD pipelines. He's proficient in Python, JavaScript, C, C++, and MySQL.",
    },
    "skills": {
        "response": "Carson is proficient in Python, JavaScript, C, C++, and MySQL. He has hands-on experience with React, Flask, full-stack development, agile methodologies, and CI/CD pipeline development.",
    },
    "projects": {
        "response": "Carson has built several projects, including this portfolio site with a rule-based AI chatbot backend, and various full-stack applications. Check out the Projects section on this page for the full list!",
    },
    "experience": {
        "response": "Carson has experience in full-stack development, agile development practices, and CI/CD pipeline development, gained through coursework and personal projects at Ontario Tech University.",
    },
    "education": {
        "response": "Carson is currently a 3rd year Software Engineering student at Ontario Tech University, expected to graduate in 2027.",
    },
    "contact": {
        "response": "You can reach Carson at carsonchan050505@gmail.com, on LinkedIn at linkedin.com/in/lok-yung-chan-116051327/, or on GitHub at github.com/cc555cc.",
        "details": {
            "email": "You can email Carson at carsonchan050505@gmail.com.",
            "linkedin": "Carson's LinkedIn profile: linkedin.com/in/lok-yung-chan-116051327/",
            "github": "Carson's GitHub: github.com/cc555cc",
            "instagram": "Carson's Instagram: instagram.com/lokk_0555/",
        },
    },
    "resume": {
        "response": {"action": "download_resume", "text": "Here's Carson's resume! Click the button below to download it."},
    },
}
